import type { Article } from './types'
import whyInternationalInvesting from './content/why-international-investing-matters-2026'
import lrsExplained from './content/lrs-explained'
import currencyRiskExplained from './content/currency-risk-explained'
import globalTaxes from './content/global-taxes'
import rsuTaxation from './content/rsu-taxation'
import feederVsComboFunds from './content/feeder-vs-combo-funds'
import giftCity from './content/gift-city'
import globalInvestmentAllocation from './content/global-investment-allocation'
import routesForInternationalInvesting from './content/routes-for-international-investing'

// SEO content cluster, August 2026
import howToInvestUsStocks from './content/how-to-invest-in-us-stocks-from-india'
import taxOnUsStocks from './content/tax-on-us-stocks-in-india'
import usMarketTimings from './content/us-stock-market-timings-india'
import isUsInvestingSafe from './content/is-investing-in-us-stocks-safe-and-legal'
import howToInvestSp500 from './content/how-to-invest-in-sp500-from-india'
import scheduleFa from './content/schedule-fa-foreign-assets-reporting'
import dividendTax from './content/dividend-tax-us-stocks-india'
import tcsOnLrs from './content/tcs-on-lrs-explained'
import dtaaFtc from './content/dtaa-india-us-foreign-tax-credit'
import usEstateTax from './content/us-estate-tax-indian-investors'
import w8benExplained from './content/w8ben-form-explained'
import reportUsStocksItr from './content/how-to-report-us-stocks-in-itr'
import nyseNasdaqIndices from './content/nyse-nasdaq-and-us-indices-explained'
import fractionalShares from './content/fractional-shares-explained'
import usVsIndianStocks from './content/us-stocks-vs-indian-stocks'
import bestUsEtfs from './content/best-us-etfs-for-indian-investors'
import minimumInvestment from './content/minimum-investment-and-costs-us-stocks'
import transferMoney from './content/how-to-transfer-money-for-us-stock-investing'
import withdrawMoney from './content/how-to-withdraw-money-from-us-stocks-to-india'
import etfVsIndexFund from './content/etf-vs-index-fund-vs-mutual-fund'
import internationalBeyondUs from './content/international-stocks-beyond-the-us'

// Order = display order. The first three are the featured articles shown on the Media page.
export const ARTICLES: Article[] = [
  {
    slug: 'why-international-investing-matters-2026',
    title: 'Why International Investing Will Matter More Than Ever by 2026',
    category: 'International',
    topics: ['global-investing', 'getting-started'],
    date: '2026-01-01',
    dateLabel: 'January 2026',
    readTime: '7 min read',
    excerpt: "As we move into 2026, the case for global diversification is stronger than ever — here's why Indian investors should take notice.",
    logo: '/article-1-logo.webp',
    description: 'For Indian investors, international investing is no longer optional. Discover why US Stocks and ETFs are becoming essential for portfolio resilience in 2026 and beyond.',
    bodyHtml: whyInternationalInvesting,
    featured: true,
  },
  {
    slug: 'lrs-explained',
    title: 'LRS Explained: How Indian Residents Can Invest Overseas',
    category: 'LRS & Compliance',
    topics: ['lrs-and-compliance', 'getting-started'],
    date: '2026-06-23',
    dateLabel: 'June 2026',
    readTime: '6 min read',
    excerpt: 'The Liberalised Remittance Scheme is the gateway to overseas investing — how the USD 250,000 limit, TCS, and foreign-asset reporting actually work.',
    logo: '/article-2-logo.jpg',
    description: 'A practical guide to the Liberalised Remittance Scheme (LRS) — the USD 250,000 limit, banking process, TCS, foreign asset reporting, and how Indian residents legally invest in US Stocks and ETFs.',
    bodyHtml: lrsExplained,
    featured: true,
  },
  {
    slug: 'currency-risk-explained',
    title: 'Currency Risk Explained: Why the Rupee-Dollar Movement Matters',
    category: 'Currency',
    topics: ['global-investing', 'us-stocks'],
    date: '2026-06-23',
    dateLabel: 'June 2026',
    readTime: '5 min read',
    excerpt: 'When you invest abroad, returns ride on two things — the asset and the rupee. See how INR-USD moves can lift or trim your gains.',
    logo: '/article-3-logo.jpg',
    description: 'For Indian investors in US Stocks and ETFs, returns depend on more than performance — the rupee-dollar exchange rate matters too. Understand currency risk, with worked examples, before you invest overseas.',
    bodyHtml: currencyRiskExplained,
    featured: true,
  },
  {
    slug: 'global-taxes',
    title: 'Global Taxes: What Indian Investors Need To Know',
    category: 'Taxation',
    topics: ['taxation', 'global-investing'],
    date: '2026-06-23',
    dateLabel: 'June 2026',
    readTime: '8 min read',
    excerpt: 'The same global exposure can be taxed very differently depending on the route used — capital gains, dividends, withholding tax, LRS TCS, and foreign-asset reporting across US stocks, ETFs, feeder funds, and GIFT City.',
    logo: '/articles/global-taxes.jpg',
    description: 'How global investments are taxed for Indian investors — capital gains, dividends, US withholding tax, LRS TCS, and foreign-asset reporting across direct US stocks, ETFs, Indian feeder funds, and GIFT City structures.',
    bodyHtml: globalTaxes,
  },
  {
    slug: 'rsu-taxation',
    title: 'RSU Taxation Explained for Indian Employees Holding US Shares',
    category: 'Taxation',
    topics: ['taxation', 'us-stocks'],
    date: '2026-06-23',
    dateLabel: 'June 2026',
    readTime: '7 min read',
    excerpt: 'How US RSUs are taxed for Indian employees — tax at vesting, capital gains on sale, dividend withholding, Schedule FA reporting, and the concentration risk of holding too much employer stock.',
    logo: '/articles/rsu-taxation.jpg',
    description: 'A practical guide to how US RSUs are taxed for Indian employees — tax at vesting, capital gains on sale, dividend withholding, Schedule FA reporting, and concentration risk.',
    bodyHtml: rsuTaxation,
  },
  {
    slug: 'feeder-vs-combo-funds',
    title: 'Global Investing Made Simple: International Mutual Funds — Feeder vs Combo',
    category: 'Mutual Funds',
    topics: ['etfs-and-funds', 'global-investing'],
    date: '2026-06-23',
    dateLabel: 'June 2026',
    readTime: '6 min read',
    excerpt: 'International mutual funds let Indian investors access global markets, but feeder funds and combo funds work very differently. A breakdown of each structure and how they compare to direct US Stocks and ETFs.',
    logo: '/articles/feeder-vs-combo-funds.jpg',
    description: 'Feeder funds vs combo (fund-of-funds) international mutual funds for Indian investors — how each structure works, their trade-offs, and how they compare to direct US Stocks and ETFs.',
    bodyHtml: feederVsComboFunds,
  },
  {
    slug: 'gift-city',
    title: "GIFT City: India's Gateway to Global Investing",
    category: 'GIFT City',
    topics: ['global-investing', 'lrs-and-compliance', 'getting-started'],
    date: '2026-06-23',
    dateLabel: 'June 2026',
    readTime: '6 min read',
    excerpt: "GIFT City and India's IFSC give investors a regulated, India-linked gateway to global markets — how the route works under the LRS, and the tax, currency, and regulatory factors to weigh.",
    logo: '/articles/gift-city.jpg',
    description: "How GIFT City and India's International Financial Services Centre (IFSC) give Indian investors a regulated gateway to US stocks and ETFs under the LRS — with the tax, currency, and regulatory factors to weigh.",
    bodyHtml: giftCity,
  },
  {
    slug: 'global-investment-allocation',
    title: 'Global Investment Allocation: A Guide for ₹5K to ₹5L Monthly Investors',
    category: 'Allocation',
    topics: ['global-investing', 'getting-started'],
    date: '2026-06-23',
    dateLabel: 'June 2026',
    readTime: '8 min read',
    excerpt: 'How much of your portfolio should be global? Practical allocation ranges for Indian investors saving ₹5,000 to ₹5 lakh a month — factoring in goals, RSUs, currency risk, LRS, TCS, and tax reporting.',
    logo: '/articles/global-investment-allocation.jpg',
    description: 'Practical global allocation ranges for Indian investors saving ₹5,000 to ₹5 lakh per month — balancing goals, RSUs, currency risk, the LRS limit, TCS, and tax reporting.',
    bodyHtml: globalInvestmentAllocation,
  },
  {
    slug: 'routes-for-international-investing',
    title: 'Routes for International Investing: Intl MFs, ETFs, Stocks & GIFT City',
    category: 'Getting Started',
    topics: ['getting-started', 'global-investing', 'etfs-and-funds'],
    date: '2026-06-23',
    dateLabel: 'June 2026',
    readTime: '7 min read',
    excerpt: 'Indian investors can go global through international mutual funds, US stocks, US ETFs, or GIFT City — each differing in ownership, control, taxation, and currency exposure. A side-by-side comparison.',
    logo: '/articles/routes-for-international-investing.jpg',
    description: 'A comparison of the routes Indian investors use to go global — international mutual funds, US stocks, US ETFs, and GIFT City-linked access — across ownership, control, taxation, and currency exposure.',
    bodyHtml: routesForInternationalInvesting,
  },
  {
    slug: "how-to-invest-in-us-stocks-from-india",
    title: "How to Invest in US Stocks from India: A Step-by-Step Guide",
    category: "US Stocks",
    topics: ["us-stocks", "getting-started"],
    date: '2026-08-11',
    dateLabel: 'August 2026',
    readTime: "7 min read",
    excerpt: "The full process end to end — KYC, Form W-8BEN, remitting under the LRS, placing your first trade, and the records you will need at tax time.",
    logo: '/articles/how-to-invest-in-us-stocks-from-india.jpg',
    description: "A complete step-by-step guide to investing in US stocks from India: LRS remittance, KYC, Form W-8BEN, fractional shares, real costs, custody and taxation. Updated August 2026.",
    bodyHtml: howToInvestUsStocks,
    faqs: [
      { q: "Can an Indian resident legally buy US stocks?", a: "Yes. Indian residents can invest in US-listed stocks and ETFs under the RBI's Liberalised Remittance Scheme, which permits remittances of up to USD 250,000 per individual per financial year for permitted purposes, including overseas equity investment." },
      { q: "How much money do I need to start?", a: "There is no prescribed minimum and no account opening or maintenance charges. Because fractional shares are supported, the share price is not a barrier. The practical constraint is remittance cost, which is largely fixed per transfer, so fewer and larger transfers are more efficient than frequent small ones." },
      { q: "Do I need to file Form W-8BEN?", a: "Yes, if you hold anything that pays dividends. Filing it reduces US withholding tax on dividends from the 30% default to the 25% rate available under the India-US DTAA. It is generally valid until the end of the third succeeding calendar year." },
      { q: "How long does it take to open an account?", a: "Account opening is instant for resident Indians where there are no blockers, and up to 48 hours for NRIs and foreign nationals. Funds can only be added once the account is approved, because the brokerage account number is generated at the end of KYC." },
      { q: "Where are my shares held?", a: "Securities are custodised in the name of ViewTrade IFSC with DTCC for the benefit of customers. Shares are held in ViewTrade IFSC's name rather than the customer's, to protect clients under US regulations, but the ownership and benefit of the account belong to you as the end client." },
    ],
  },
  {
    slug: "tax-on-us-stocks-in-india",
    title: "Tax on US Stocks in India: Capital Gains, Dividends and Reporting",
    category: "Taxation",
    topics: ["taxation", "us-stocks"],
    date: '2026-08-11',
    dateLabel: 'August 2026',
    readTime: "7 min read",
    excerpt: "LTCG at 12.5% over 24 months, STCG at slab, why the ₹1.25 lakh exemption does not apply, how USD gains convert to rupees, and what each schedule of your ITR needs.",
    logo: '/articles/tax-on-us-stocks-in-india.jpg',
    description: "How US stocks are taxed for Indian investors: 12.5% LTCG over 24 months, STCG at slab rate, dividend withholding, SBI TT conversion, ITR-2 and Schedule FA. Updated August 2026.",
    bodyHtml: taxOnUsStocks,
    faqs: [
      { q: "What is the tax on long-term capital gains from US stocks in India?", a: "Gains on US stocks and ETFs held for more than 24 months are long-term capital gains, taxed at 12.5% without indexation, plus applicable surcharge and cess. The rate applies to transfers on or after 23 July 2024." },
      { q: "Does the ₹1.25 lakh LTCG exemption apply to US stocks?", a: "No. That exemption applies to Indian listed equity and equity-oriented mutual funds only. Long-term gains on US stocks and ETFs are taxable from the first rupee." },
      { q: "Do I pay capital gains tax in the United States?", a: "No. Indian residents do not pay US tax on capital gains from US shares. Capital gains are taxed only in India. The US does withhold tax on dividends." },
      { q: "What exchange rate do I use to compute the gain?", a: "The generally applied basis is the SBI TT buying rate on the last day of the month immediately preceding the month of sale. Both the purchase and sale legs are converted on this basis." },
      { q: "Which ITR form do I need to file?", a: "Holding foreign assets rules out ITR-1 and ITR-4. Most investors file ITR-2; those with business or professional income file ITR-3." },
      { q: "Do I have to report US shares if I made no profit?", a: "Yes. Schedule FA disclosure is triggered by holding the foreign asset, not by selling it or earning from it. A year with no transactions still requires disclosure." },
    ],
  },
  {
    slug: "us-stock-market-timings-india",
    title: "US Stock Market Timings in India (IST): Hours and Sessions",
    category: "US Market",
    topics: ["us-market", "getting-started"],
    date: '2026-08-11',
    dateLabel: 'August 2026',
    readTime: "4 min read",
    excerpt: "7:00 PM to 1:30 AM IST for most of the year, 8:00 PM to 2:30 AM for the rest — why the hour shifts twice a year, and why pre-market and after-hours are not equivalent.",
    logo: '/articles/us-stock-market-timings-india.jpg',
    description: "US stock market timings in Indian Standard Time: regular hours, the daylight saving shift, pre-market and after-hours sessions, and US market holidays. Updated August 2026.",
    bodyHtml: usMarketTimings,
    faqs: [
      { q: "What time does the US stock market open in India?", a: "The US regular session runs 7:00 PM to 1:30 AM IST during US daylight saving time, roughly March to November, and 8:00 PM to 2:30 AM IST during US standard time, roughly November to March." },
      { q: "Why do US market timings change twice a year?", a: "The United States observes daylight saving time and India does not, so the offset between the two is not constant. The changeover happens on the second Sunday in March and the first Sunday in November." },
      { q: "Can I trade US stocks outside regular hours?", a: "Pre-market and after-hours sessions exist, corresponding to roughly 4:00 PM to 7:00 PM IST and from 1:30 AM IST onwards. Liquidity is thinner and bid-ask spreads are wider than in the regular session, so orders can fill further from the last traded price." },
      { q: "Do I need to stay awake until the US market closes?", a: "No. Limit orders let you specify your price in advance rather than watching a screen. For a long-term investor the exact minute of execution rarely determines the outcome." },
      { q: "Are US market holidays the same as Indian ones?", a: "No. US markets close on US public holidays such as Thanksgiving, Independence Day and Labor Day, which have no Indian equivalent. There are also occasional early closes. Check the current year schedule." },
    ],
  },
  {
    slug: "is-investing-in-us-stocks-safe-and-legal",
    title: "Is Investing in US Stocks Safe and Legal for Indian Residents?",
    category: "US Stocks",
    topics: ["us-stocks", "lrs-and-compliance", "getting-started"],
    date: '2026-08-11',
    dateLabel: 'August 2026',
    readTime: "5 min read",
    excerpt: "The RBI scheme that makes it legal, who regulates the account, where your shares are actually custodied, what SIPC covers — and the risks that are genuinely real.",
    logo: '/articles/is-investing-in-us-stocks-safe-and-legal.jpg',
    description: "Is it legal and safe for Indian residents to invest in US stocks? The LRS basis, IFSCA regulation, DTCC custody, SIPC coverage and its limits, and the risks that genuinely apply.",
    bodyHtml: isUsInvestingSafe,
    faqs: [
      { q: "Is it legal for an Indian resident to invest in US stocks?", a: "Yes. The RBI's Liberalised Remittance Scheme permits resident individuals to remit up to USD 250,000 per financial year for permitted purposes, and overseas equity investment is one of them. Compliance requires TCS on remittances above the threshold and Schedule FA disclosure in your return." },
      { q: "Who regulates my account?", a: "Accounts opened through Platizio Global are held with ViewTrade IFSC, regulated by the International Financial Services Centres Authority in GIFT City. This is an IFSC-regulated account, not a standard US brokerage account." },
      { q: "In whose name are my shares held?", a: "Securities are custodised in the name of ViewTrade IFSC with DTCC for the benefit of customers. The shares are held in ViewTrade IFSC's name rather than yours individually, which is the standard structure for client assets under US regulations, but the ownership and benefit belong to you as the end client." },
      { q: "What happens if the broker fails?", a: "US brokerage accounts are covered by SIPC up to USD 500,000 in total, including up to USD 250,000 for cash. SIPC protects against the failure of a brokerage firm; it does not protect against a fall in the market value of your investments." },
      { q: "What are the real risks?", a: "Market risk, currency risk from rupee-dollar movement, concentration risk given how heavily US indices weight a few large technology companies, tax and reporting complexity, and US estate tax exposure above USD 60,000 of US-situs assets." },
    ],
  },
  {
    slug: "how-to-invest-in-sp500-from-india",
    title: "How to Invest in the S&P 500 from India: Three Routes Compared",
    category: "ETFs",
    topics: ["etfs-and-funds", "us-stocks", "getting-started"],
    date: '2026-08-11',
    dateLabel: 'August 2026',
    readTime: "5 min read",
    excerpt: "Direct US ETF, Indian feeder fund or GIFT City — the same index, three quite different outcomes on ownership, currency, disclosure and tax.",
    logo: '/articles/how-to-invest-in-sp500-from-india.jpg',
    description: "Three ways to invest in the S&P 500 from India compared: direct US-listed ETFs, Indian feeder funds and GIFT City routes, on ownership, cost, currency and tax treatment.",
    bodyHtml: howToInvestSp500,
    faqs: [
      { q: "What is the simplest way to invest in the S&P 500 from India?", a: "There are three common routes: buying a US-listed S&P 500 ETF directly under the LRS, buying an Indian feeder fund that invests into an overseas fund tracking the index, or a GIFT City structure. They differ in ownership, currency, cost and tax treatment rather than in the underlying index." },
      { q: "Which route is cheapest?", a: "There is no single answer. Direct US ETFs typically have lower expense ratios but add remittance costs, TCS cash flow and annual disclosure. Feeder funds avoid those but add a layer of fund costs. Over a long holding period the tax difference between routes can outweigh the difference in expense ratios." },
      { q: "Do I have to disclose an S&P 500 ETF in Schedule FA?", a: "If you hold the US-listed ETF directly, yes — it is a foreign asset and disclosure is triggered by holding it. An Indian feeder fund is an Indian scheme and does not create a Schedule FA obligation." },
      { q: "Is the S&P 500 a diversified investment?", a: "It holds 500 large US companies but is weighted by market capitalisation, so a meaningful share sits in a small number of very large technology names. It is also a US index — Europe, Japan and emerging markets are absent." },
    ],
  },
  {
    slug: "schedule-fa-foreign-assets-reporting",
    title: "Schedule FA: Reporting US Stocks and Foreign Assets in Your ITR",
    category: "Taxation",
    topics: ["taxation", "lrs-and-compliance"],
    date: '2026-08-11',
    dateLabel: 'August 2026',
    readTime: "5 min read",
    excerpt: "Disclosure is triggered by holding the asset, not by profiting from it. What to report, the calendar-year trap, peak value, and why the penalty exposure is disproportionate.",
    logo: '/articles/schedule-fa-foreign-assets-reporting.jpg',
    description: "Schedule FA explained for Indian investors holding US stocks: who must file, what to disclose, the calendar-year reporting period, peak value, and Black Money Act exposure.",
    bodyHtml: scheduleFa,
    faqs: [
      { q: "Do I have to file Schedule FA if I made no profit?", a: "Yes. The obligation is triggered by holding a foreign asset at any time during the relevant period, not by selling it or earning income from it. A year with no transactions still requires disclosure." },
      { q: "What has to be disclosed?", a: "Foreign equity and debt holdings, foreign custodial and depository accounts, RSU and ESPP holdings from a foreign employer including unsold vested shares, and any other foreign financial interest. For each you provide the entity details, date acquired, initial investment, peak value, closing value and income earned." },
      { q: "What reporting period applies?", a: "For foreign assets the relevant period has historically been referenced to the calendar year rather than the April to March Indian tax year. Because the wording has been revised across assessment years, confirm the applicable period for the year you are filing rather than carrying forward an assumption." },
      { q: "What are the penalties for not disclosing?", a: "Undisclosed foreign assets fall within the scope of the Black Money (Undisclosed Foreign Income and Assets) Act, 2015, which carries substantially heavier penalties than ordinary under-reporting under the Income Tax Act." },
      { q: "Which ITR form contains Schedule FA?", a: "ITR-2 and ITR-3. Holding foreign assets therefore rules out filing ITR-1 or ITR-4." },
    ],
  },
  {
    slug: "dividend-tax-us-stocks-india",
    title: "Dividend Tax on US Stocks for Indian Investors",
    category: "Taxation",
    topics: ["taxation", "us-stocks"],
    date: '2026-08-11',
    dateLabel: 'August 2026',
    readTime: "5 min read",
    excerpt: "25% withheld in the US, taxed again in India on the gross amount, then relieved by foreign tax credit — with a worked example showing where the money actually lands.",
    logo: '/articles/dividend-tax-us-stocks-india.jpg',
    description: "How US dividends are taxed for Indian investors: 30% default withholding, 25% under the DTAA with Form W-8BEN, Indian slab rate on the gross amount, and foreign tax credit relief.",
    bodyHtml: dividendTax,
    faqs: [
      { q: "What is the US withholding tax rate on dividends for Indian investors?", a: "The default rate for a non-resident is 30%. With Form W-8BEN on file, the India-US treaty rate of 25% applies. The 15% treaty rate requires holding at least 10% of the voting stock of the paying company and is not available to retail investors." },
      { q: "Do I pay tax again in India on the same dividend?", a: "India taxes the gross dividend — the full amount before US withholding — at your slab rate, and you then claim a foreign tax credit for the US tax already withheld. The net effect is that you generally bear roughly your Indian slab rate in total." },
      { q: "Do I report the gross or net dividend?", a: "The gross amount, before US withholding. Reporting the net amount received is one of the most common errors and understates both the income and the credit you can claim." },
      { q: "What if my Indian tax rate is lower than 25%?", a: "The foreign tax credit is generally capped at the Indian tax attributable to that income. Where the Indian rate is lower than the US withholding rate, the excess is typically not refundable, so US dividend income is less efficient for lower-slab taxpayers." },
      { q: "How do I claim the credit?", a: "By filing Form 67 and completing Schedule FSI and Schedule TR in your return. For income earned from FY 2026-27 onwards, Form 67 is replaced by Form 44." },
    ],
  },
  {
    slug: "tcs-on-lrs-explained",
    title: "TCS on LRS Remittances: 20% Above ₹10 Lakh, and How to Get It Back",
    category: "LRS & Compliance",
    topics: ["lrs-and-compliance", "taxation"],
    date: '2026-08-11',
    dateLabel: 'August 2026',
    readTime: "5 min read",
    excerpt: "TCS is a prepayment of your own tax, not a charge for investing abroad. How the cumulative threshold works, why the 2% rate does not apply, and the cost that is real.",
    logo: '/articles/tcs-on-lrs-explained.jpg',
    description: "TCS on LRS remittances explained: 20% above ₹10 lakh cumulative per PAN, why investment remittances are excluded from the 2% rate, and how to claim it back.",
    bodyHtml: tcsOnLrs,
    faqs: [
      { q: "What is the TCS rate on money sent abroad for investment?", a: "TCS applies at 20% on the amount exceeding ₹10 lakh of cumulative LRS remittances under your PAN in a financial year. The first ₹10 lakh attracts no TCS. The threshold rose from ₹7 lakh on 1 April 2025." },
      { q: "Does the reduced 2% TCS rate apply to investments?", a: "No. Budget 2026 reduced the rate to 2% for education and medical remittances. Investment remittances remain at 20%." },
      { q: "Is the threshold per transaction or per year?", a: "It is cumulative per PAN per financial year, across all banks. Four separate ₹3 lakh remittances total ₹12 lakh and the last one crosses the threshold. Banks rely on your declaration of prior remittances, so keep your own running total." },
      { q: "Do I lose the TCS money?", a: "No. TCS is a tax collected in advance, not an additional charge. It appears in Form 26AS against your PAN, is adjustable against your income tax liability, and is refundable if your liability is lower. The real effect is on cash flow and timing." },
      { q: "How do I get TCS back?", a: "Claim it in your income tax return. Alternatively, salaried taxpayers can furnish details to their employer so it is factored into TDS on salary, which reduces the interim cash-flow effect." },
    ],
  },
  {
    slug: "dtaa-india-us-foreign-tax-credit",
    title: "India-US DTAA and Foreign Tax Credit: Form 67 and Form 44",
    category: "Taxation",
    topics: ["taxation"],
    date: '2026-08-11',
    dateLabel: 'August 2026',
    readTime: "5 min read",
    excerpt: "Where the treaty actually applies, how to claim credit in India, and the Form 67 to Form 44 transition — with the years stated, because getting them backwards misdirects anyone filing now.",
    logo: '/articles/dtaa-india-us-foreign-tax-credit.jpg',
    description: "How the India-US DTAA works for investors: the 25% dividend rate, claiming foreign tax credit under Section 90 and Rule 128, and the Form 67 to Form 44 transition from FY 2026-27.",
    bodyHtml: dtaaFtc,
    faqs: [
      { q: "What does the India-US DTAA do for an investor?", a: "Two things: it caps US withholding tax on dividends at 25% for Indian tax residents with Form W-8BEN on file, and it entitles you to claim credit in India for the US tax already paid. It is not relevant to capital gains, which are taxed only in India." },
      { q: "Is it still Form 67 or has it become Form 44?", a: "Both, depending on the year. Form 67 applies to income earned in FY 2024-25 and FY 2025-26. Form 44, under Rule 76 of the Income-tax Rules 2026, applies to income earned from FY 2026-27 onwards. Anyone filing now for income already earned still uses Form 67." },
      { q: "What happens if I file Form 67 late?", a: "Rule 128 requires it on or before the return due date. A consistent line of tribunal decisions has held the requirement to be directory rather than mandatory, so a delay should not by itself extinguish the entitlement. That is helpful if you have already missed it, but relying on litigation to recover a credit you could have claimed on time is a poor plan." },
      { q: "How much credit do I actually get?", a: "Generally the lower of the foreign tax paid and the Indian tax attributable to that same income. If your Indian rate is above 25% you get full credit and pay the difference in India. If it is below 25%, the excess US withholding is generally not refundable." },
      { q: "Do I need a Tax Residency Certificate?", a: "A TRC is required in some circumstances to establish treaty eligibility. Whether one is needed for retail dividend credit depends on the facts and the assessing officer, and is worth confirming with a CA." },
    ],
  },
  {
    slug: "us-estate-tax-indian-investors",
    title: "US Estate Tax for Indian Investors: The USD 60,000 Threshold",
    category: "Taxation",
    topics: ["taxation", "us-stocks"],
    date: '2026-08-11',
    dateLabel: 'August 2026',
    readTime: "5 min read",
    excerpt: "Rates to 40% above a USD 60,000 exemption, no Indian treaty relief, and a threshold that portfolios grow into. Under-discussed, and worth knowing before you cross it.",
    logo: '/articles/us-estate-tax-indian-investors.jpg',
    description: "US estate tax for Indian investors explained: the USD 60,000 non-resident alien exemption, rates up to 40%, what counts as a US-situs asset, and why the DTAA does not help.",
    bodyHtml: usEstateTax,
    faqs: [
      { q: "Do Indian investors pay US estate tax?", a: "US-situs assets above a USD 60,000 exemption can attract US estate tax at rates up to 40% on the death of a non-resident alien owner. Indian residents are treated as non-resident aliens for this purpose." },
      { q: "Does the India-US tax treaty help?", a: "No. The India-US DTAA covers income tax; it does not address estate tax. Some countries have negotiated estate tax treaties with the US that give their residents a larger exemption. India is not among them." },
      { q: "What counts as a US-situs asset?", a: "Generally, shares of US-incorporated companies and US-domiciled ETFs and mutual funds, wherever the account is held. A fund domiciled outside the US is generally not US-situs even if it holds US shares. Where the brokerage account sits does not determine situs." },
      { q: "Does holding through a GIFT City account avoid it?", a: "Not by itself. Situs is determined by where the issuer is incorporated or the fund is domiciled, not by where the account is held." },
      { q: "Should I restructure my portfolio to avoid it?", a: "For portfolios well below USD 60,000 of US-situs assets this is not yet a live issue. Above that level it is worth a specific conversation with a cross-border tax and estate adviser, because restructuring has its own costs and can be worse overall than accepting the exposure." },
    ],
  },
  {
    slug: "w8ben-form-explained",
    title: "Form W-8BEN Explained for Indian Investors",
    category: "Taxation",
    topics: ["taxation", "us-stocks", "getting-started"],
    date: '2026-08-11',
    dateLabel: 'August 2026',
    readTime: "5 min read",
    excerpt: "A short declaration that cuts dividend withholding from 30% to 25%. What it asks for, why the address and PAN fields matter, and the silent expiry that catches people.",
    logo: '/articles/w8ben-form-explained.jpg',
    description: "Form W-8BEN explained for Indian investors: what it declares, how it reduces US dividend withholding from 30% to 25% under the DTAA, what you provide, and when it expires.",
    bodyHtml: w8benExplained,
    faqs: [
      { q: "What is Form W-8BEN?", a: "An IRS form submitted to your broker, establishing that you are not a US person and that you are a tax resident of a treaty country. For Indian residents it reduces US withholding tax on dividends from the 30% default to the 25% treaty rate." },
      { q: "Does it affect capital gains tax?", a: "No. Indian residents do not pay US tax on capital gains from US shares either way. The entire effect of W-8BEN is on dividend income." },
      { q: "How long is it valid?", a: "Generally from the date of signing until the end of the third succeeding calendar year, unless a change in circumstances makes the information incorrect before then. When it lapses without renewal, withholding reverts to 30% with no warning other than smaller dividends." },
      { q: "What do I enter as my taxpayer identification number?", a: "For Indian residents, the PAN is generally entered as the foreign TIN. Your permanent residence address must be a genuine Indian residential address." },
      { q: "What is the difference between W-8BEN and W-8BEN-E?", a: "W-8BEN is for individuals. W-8BEN-E is for entities such as companies, trusts and partnerships. An individual investor needs W-8BEN." },
    ],
  },
  {
    slug: "how-to-report-us-stocks-in-itr",
    title: "How to Report US Stocks in Your ITR: A Step-by-Step Walkthrough",
    category: "Taxation",
    topics: ["taxation", "lrs-and-compliance"],
    date: '2026-08-11',
    dateLabel: 'August 2026',
    readTime: "5 min read",
    excerpt: "Which form, which schedules, how to convert USD gains, where the foreign tax credit goes, and the six mistakes that cause most of the trouble.",
    logo: '/articles/how-to-report-us-stocks-in-itr.jpg',
    description: "A step-by-step guide to reporting US stocks in your Indian tax return: ITR-2 vs ITR-3, Schedules CG, OS, FSI, TR and FA, currency conversion, Form 67 and claiming TCS.",
    bodyHtml: reportUsStocksItr,
    faqs: [
      { q: "Which ITR form should I file if I hold US stocks?", a: "Holding foreign assets rules out ITR-1 and ITR-4 because neither contains Schedule FA. Most investors file ITR-2; those with business or professional income file ITR-3." },
      { q: "Which schedules do I need to complete?", a: "Schedule CG for capital gains on sales, Schedule OS for dividend income, Schedule FSI for foreign-source income, Schedule TR for tax relief claimed, and Schedule FA for the foreign assets themselves. Schedule FA applies whether or not you sold anything." },
      { q: "What exchange rate should I use?", a: "The generally applied basis is the SBI TT buying rate on the last day of the month immediately preceding the month of the transaction, applied to both the purchase and the sale legs." },
      { q: "How do I claim the TCS deducted on my remittances?", a: "TCS appears in Form 26AS against your PAN. It is adjustable against your total tax liability and refundable to the extent it exceeds it. Claim it in your return." },
      { q: "What are the most common mistakes?", a: "Filing ITR-1 while holding foreign assets, using a 12-month holding period instead of 24, claiming the ₹1.25 lakh LTCG exemption on foreign shares, reporting net rather than gross dividends, forgetting Form 67, and skipping Schedule FA in a year with no transactions." },
    ],
  },
  {
    slug: "nyse-nasdaq-and-us-indices-explained",
    title: "NYSE, NASDAQ and the US Indices Explained",
    category: "US Market",
    topics: ["us-market", "etfs-and-funds"],
    date: '2026-08-11',
    dateLabel: 'August 2026',
    readTime: "5 min read",
    excerpt: "Exchanges are where shares trade; indices measure baskets of them. What separates the S&P 500, Nasdaq 100 and Dow — and why the most quoted is the least useful.",
    logo: '/articles/nyse-nasdaq-and-us-indices-explained.jpg',
    description: "NYSE vs NASDAQ, and what the S&P 500, Dow Jones and Nasdaq 100 actually measure. How index construction and weighting affect the ETFs that track them.",
    bodyHtml: nyseNasdaqIndices,
    faqs: [
      { q: "What is the difference between NYSE and NASDAQ?", a: "Both are US stock exchanges. The NYSE is older and has historically used a hybrid model with designated market makers on a physical floor; NASDAQ is fully electronic with competing market makers and a heavier concentration of technology listings. For a retail investor buying a listed share the practical difference is minimal." },
      { q: "What is the difference between an exchange and an index?", a: "An exchange is a venue where shares change hands. An index is a measurement of a basket of shares. A company listed on NASDAQ may well be a member of the S&P 500; the two facts are unrelated." },
      { q: "What is the difference between the S&P 500, the Dow and the Nasdaq 100?", a: "The S&P 500 tracks 500 large US companies weighted by market capitalisation. The Nasdaq 100 tracks the largest 100 non-financial companies listed on NASDAQ, so it is technology-heavy. The Dow tracks 30 companies weighted by share price rather than company size, which makes it the least representative of the three." },
      { q: "Why is the Dow considered less useful?", a: "Because it weights by share price. A company with a USD 500 share price influences the index more than one with a USD 50 share price regardless of which is the larger business, and a share split changes a company weight without changing anything about the company." },
      { q: "Is the S&P 500 a global index?", a: "No. It is a US index. Europe, Japan and emerging markets are entirely absent from it." },
    ],
  },
  {
    slug: "fractional-shares-explained",
    title: "Fractional Shares Explained for Indian Investors",
    category: "US Stocks",
    topics: ["us-stocks", "getting-started"],
    date: '2026-08-11',
    dateLabel: 'August 2026',
    readTime: "5 min read",
    excerpt: "Invest an amount rather than a quantity. How fractions handle dividends and splits, why they suit monthly investing, and the one limitation worth knowing before you rely on them.",
    logo: '/articles/fractional-shares-explained.jpg',
    description: "Fractional shares explained for Indian investors: how they work, dividends and corporate actions on fractions, tax treatment, and why they generally cannot be transferred between brokers.",
    bodyHtml: fractionalShares,
    faqs: [
      { q: "What is a fractional share?", a: "A portion of a whole share. If a share trades at USD 1,000 and you invest USD 100, you receive 0.1 of a share. The percentage return on a fraction is identical to that on a whole share." },
      { q: "Do fractional shares receive dividends?", a: "Yes, proportionally. Holding 0.1 of a share paying USD 4 per share yields USD 0.40, subject to US withholding at 25% with Form W-8BEN on file." },
      { q: "What happens to fractions in a stock split?", a: "Splits apply proportionally. A 2-for-1 split turns 0.1 of a share into 0.2." },
      { q: "Can I transfer fractional shares to another broker?", a: "Generally not. Standard US transfer mechanisms handle whole shares, so fractions typically have to be sold and the cash moved instead. Selling is a taxable event, which a transfer would not be." },
      { q: "Are fractional shares taxed differently?", a: "No. They are taxed exactly as whole shares: long-term at 12.5% if held more than 24 months, short-term at slab rate otherwise, with Schedule FA disclosure applying as to any foreign asset." },
    ],
  },
  {
    slug: "us-stocks-vs-indian-stocks",
    title: "US Stocks vs Indian Stocks: What Actually Differs",
    category: "International",
    topics: ["us-stocks", "global-investing"],
    date: '2026-08-11',
    dateLabel: 'August 2026',
    readTime: "5 min read",
    excerpt: "Sector composition, currency, tax treatment and correlation compared — and why the useful question is how much of each rather than which one.",
    logo: '/articles/us-stocks-vs-indian-stocks.jpg',
    description: "US stocks vs Indian stocks compared for Indian investors: sector composition, currency exposure, tax treatment, trading hours, correlation and how to think about allocation.",
    bodyHtml: usVsIndianStocks,
    faqs: [
      { q: "Should I invest in US stocks or Indian stocks?", a: "For most investors it is not a choice between them. Indian and US markets contain different companies, respond to different economic cycles and are denominated in different currencies, which is precisely why holding both does something that holding either alone does not." },
      { q: "What sectors does the Indian market lack?", a: "Indian indices are weighted towards financials, energy, IT services and consumer goods. Global software platforms, semiconductor designers and large-scale pharmaceutical research have essentially no representation on Indian exchanges, simply because those companies are listed elsewhere." },
      { q: "How does the tax treatment differ?", a: "The two largest differences are the holding period and the exemption. Indian listed equity qualifies for long-term treatment after 12 months and benefits from the ₹1.25 lakh LTCG exemption. US stocks require more than 24 months and get no such exemption. US holdings also require Schedule FA disclosure every year." },
      { q: "Are Indian and US markets correlated?", a: "Imperfectly. They respond to different domestic cycles and currencies, which is what makes diversification work. But correlation is not zero, and in sharp global risk-off episodes most equity markets fall together." },
      { q: "How much should I allocate to each?", a: "There is no single correct split. What bears on it is your existing exposure — including any RSUs in a US employer — your time horizon, whether you have future dollar liabilities such as overseas education, and your appetite for the additional annual reporting." },
    ],
  },
  {
    slug: "best-us-etfs-for-indian-investors",
    title: "How to Evaluate US ETFs as an Indian Investor",
    category: "ETFs",
    topics: ["etfs-and-funds", "us-stocks"],
    date: '2026-08-11',
    dateLabel: 'August 2026',
    readTime: "5 min read",
    excerpt: "Not a list of funds to buy. The criteria that actually separate one ETF from another — including two that matter specifically to Indian investors and appear on no factsheet.",
    logo: '/articles/best-us-etfs-for-indian-investors.jpg',
    description: "How Indian investors should evaluate US ETFs: exposure type, expense ratio, AUM, liquidity, tracking difference, and the dividend withholding and estate tax situs issues nobody mentions.",
    bodyHtml: bestUsEtfs,
    faqs: [
      { q: "What should I look at when comparing US ETFs?", a: "Expense ratio, assets under management, trading liquidity and bid-ask spread, realised tracking difference against the index, and the index methodology itself. For an Indian investor, dividend withholding and the fund domicile deserve equal billing." },
      { q: "Why does dividend withholding matter when comparing ETFs?", a: "A US-domiciled ETF distributing dividends has 25% withheld at source for an Indian resident with Form W-8BEN on file, and the Indian foreign tax credit is capped at the Indian tax on that income. This reduces your effective return and does not appear in the expense ratio." },
      { q: "What is tracking difference?", a: "The realised gap between the fund and its index after costs. It is more informative than tracking error, which measures the variability of that gap. A fund that consistently lags its index does its job less well than the headline expense ratio suggests." },
      { q: "Does fund domicile matter?", a: "Yes, for estate tax. US-domiciled ETFs are US-situs assets, and above a USD 60,000 threshold they fall within the scope of US estate tax for non-resident aliens at rates up to 40%, with no Indian treaty relief." },
      { q: "Should I start with a thematic ETF?", a: "Thematic funds are the narrowest and most volatile category, and themes can stay out of favour for years. Broad-market exposure is the usual starting point; a thematic fund is a considered position rather than a foundation." },
    ],
  },
  {
    slug: "minimum-investment-and-costs-us-stocks",
    title: "Minimum Investment and the Real Costs of US Investing",
    category: "US Stocks",
    topics: ["us-stocks", "lrs-and-compliance", "getting-started"],
    date: '2026-08-11',
    dateLabel: 'August 2026',
    readTime: "5 min read",
    excerpt: "There is no account minimum and no share-price barrier. The real floor is set by remittance costs, which are largely fixed per transfer — and that changes how you should invest monthly.",
    logo: '/articles/minimum-investment-and-costs-us-stocks.jpg',
    description: "What it really costs to invest in US stocks from India: no account minimum, forex markup, wire fees, brokerage, and why TCS is a cash-flow effect rather than a cost.",
    bodyHtml: minimumInvestment,
    faqs: [
      { q: "What is the minimum amount needed to invest in US stocks from India?", a: "There is no prescribed minimum and no account opening or maintenance charges. Fractional shares mean the share price is not a barrier. The practical floor is set by remittance costs, which are largely fixed per transfer rather than proportional to the amount." },
      { q: "What are the actual costs?", a: "A bank wire or SWIFT fee, fixed per transfer; forex markup embedded in the exchange rate, which is proportional and rarely quoted; and brokerage per trade. TCS above ₹10 lakh is recoverable and is not a cost." },
      { q: "Should I remit money monthly like a SIP?", a: "Generally not. Because the wire fee is fixed per transfer, monthly remittances pay it twelve times a year. A more efficient pattern is to accumulate in rupees and remit in larger tranches, then deploy from the dollar balance as often as you like — trading inside the account incurs no remittance cost." },
      { q: "What is forex markup?", a: "The spread between the interbank rate and the rate your bank actually gives you. It is embedded in the exchange rate rather than shown as a line item, which is why it goes unnoticed. It varies between banks more than most people expect." },
    ],
  },
  {
    slug: "how-to-transfer-money-for-us-stock-investing",
    title: "How to Transfer Money Abroad for US Stock Investing",
    category: "LRS & Compliance",
    topics: ["lrs-and-compliance", "getting-started"],
    date: '2026-08-11',
    dateLabel: 'August 2026',
    readTime: "5 min read",
    excerpt: "Form A2, purpose codes, SWIFT and timelines — plus the forex markup that is usually the largest cost and the least visible, and why the TCS threshold is cumulative.",
    logo: '/articles/how-to-transfer-money-for-us-stock-investing.jpg',
    description: "How to remit money from India to a US brokerage account: Form A2, purpose codes, SWIFT timelines, forex markup, and the cumulative TCS threshold per PAN.",
    bodyHtml: transferMoney,
    faqs: [
      { q: "How do I send money to my US brokerage account?", a: "Generate the remittance instructions from within the platform, complete Form A2 with the correct purpose code for overseas investment, and initiate the transfer through your bank. Your bank converts rupees to dollars and sends the funds via SWIFT." },
      { q: "How long does the transfer take?", a: "Typically a few business days. International transfers pass through correspondent banks, and weekends or public holidays in either country extend the timeline." },
      { q: "What is Form A2?", a: "The declaration under FEMA that accompanies an outward remittance. It states the amount, the beneficiary and the purpose code. For overseas equity investment the purpose code must reflect that — selecting travel or maintenance of relatives misclassifies the remittance." },
      { q: "Can I fund the account before it is approved?", a: "No. The brokerage account number is generated at the end of KYC, so the account must be open and approved before you can remit to it." },
      { q: "Does travel spending count against my LRS limit?", a: "Yes. The USD 250,000 annual limit applies across all permitted purposes, so overseas travel, education and gifts all draw on the same allowance as investment." },
    ],
  },
  {
    slug: "how-to-withdraw-money-from-us-stocks-to-india",
    title: "How to Withdraw Money from US Stocks Back to India",
    category: "LRS & Compliance",
    topics: ["lrs-and-compliance", "us-stocks"],
    date: '2026-08-11',
    dateLabel: 'August 2026',
    readTime: "5 min read",
    excerpt: "Sell, settle on T+1, request withdrawal, receive funds in your own account. The exit path in full, including why the tax event is the sale rather than the repatriation.",
    logo: '/articles/how-to-withdraw-money-from-us-stocks-to-india.jpg',
    description: "How to repatriate money from US stocks to India: the sell-settle-withdraw sequence, T+1 settlement, why the receiving account must be in your own name, timelines and tax treatment.",
    bodyHtml: withdrawMoney,
    faqs: [
      { q: "How do I withdraw money from my US brokerage account?", a: "Sell the securities, wait for T+1 settlement, then place a withdrawal request from the platform specifying the amount and your bank details. Funds are remitted to your Indian bank account and converted to rupees." },
      { q: "Can I withdraw to a family member bank account?", a: "No. The receiving account must be in your own name. Funds remitted abroad under the LRS must return to the remitter, so a spouse or parent account, or a business account, cannot be used." },
      { q: "How long does a withdrawal take?", a: "Plan on the better part of a week end to end: the sale executes within the session, settlement takes one business day, then the international transfer typically takes a few business days. Weekends and holidays in either country extend it." },
      { q: "Is tax triggered by selling or by bringing the money home?", a: "By selling. Capital gains arise when you sell the security, whether or not you repatriate. An investor who sells and leaves the cash in the brokerage account has the same liability as one who withdraws immediately." },
      { q: "Does TCS apply to money coming back to India?", a: "No. TCS is collected on outward remittance under the LRS. Repatriation is not a remittance abroad and does not attract it." },
    ],
  },
  {
    slug: "etf-vs-index-fund-vs-mutual-fund",
    title: "ETF vs Index Fund vs Mutual Fund: What Actually Differs",
    category: "ETFs",
    topics: ["etfs-and-funds", "getting-started"],
    date: '2026-08-11',
    dateLabel: 'August 2026',
    readTime: "5 min read",
    excerpt: "Two different questions get merged here — how a fund picks holdings, and how you trade it. Separating them makes the choice, and the tax consequences, much clearer.",
    logo: '/articles/etf-vs-index-fund-vs-mutual-fund.jpg',
    description: "ETF vs index fund vs mutual fund explained: passive versus active, exchange-traded versus fund-house dealt, and how the route you choose changes tax treatment for Indian investors.",
    bodyHtml: etfVsIndexFund,
    faqs: [
      { q: "What is the difference between an ETF and an index fund?", a: "They answer different questions. Index fund describes how the fund picks holdings — it tracks an index rather than exercising judgement. ETF describes how you trade it — on an exchange throughout the session rather than at end-of-day NAV. A fund can be both." },
      { q: "Can an ETF be actively managed?", a: "Yes. Active ETFs are a growing category. Being exchange-traded says nothing about whether a manager selects the holdings." },
      { q: "Which is cheaper?", a: "Passive products of either structure are generally cheaper than active ones. ETFs add a cost that funds do not have: the bid-ask spread, paid on entry and exit, which does not appear in the expense ratio. For a thinly traded ETF that spread can outweigh a lower expense ratio." },
      { q: "Does it matter whether I hold a US ETF directly or an Indian international fund?", a: "Considerably. A directly held US ETF is a foreign asset: dollar-denominated, using your LRS limit, attracting TCS above the threshold, requiring Schedule FA disclosure, and taxed at 12.5% after 24 months. An Indian scheme avoids all of that and is taxed by its own category. They can track the same index and still differ substantially." },
    ],
  },
  {
    slug: "international-stocks-beyond-the-us",
    title: "International Stocks Beyond the US: Europe, Japan and Emerging Markets",
    category: "International",
    topics: ["us-market", "global-investing", "etfs-and-funds"],
    date: '2026-08-11',
    dateLabel: 'August 2026',
    readTime: "5 min read",
    excerpt: "A US brokerage account reaches further than US companies. ADRs and US-listed international ETFs, what they actually diversify, and where the returns diminish.",
    logo: '/articles/international-stocks-beyond-the-us.jpg',
    description: "How Indian investors can access Europe, Japan and emerging markets through a US brokerage account using ADRs and US-listed international ETFs, and what that actually diversifies.",
    bodyHtml: internationalBeyondUs,
    faqs: [
      { q: "Can I invest outside the US through a US brokerage account?", a: "Yes. American Depositary Receipts represent shares in foreign companies but trade on US exchanges in dollars, and US-listed international ETFs hold baskets of non-US companies. Neither requires an additional account or currency." },
      { q: "What is an ADR?", a: "A US-listed instrument representing shares in a foreign company. It trades on a US exchange in dollars and settles like any other US security. The depositary bank charges a periodic custody fee, often deducted from dividends, and the underlying country may withhold tax on dividends before they reach you." },
      { q: "Does international exposure remove currency risk?", a: "No, it changes it. A US-listed fund holding European companies is priced in dollars but its underlying value moves with the euro, so you end up with exposure to the underlying currencies regardless of the dollar wrapper." },
      { q: "Is the tax treatment different from US shares?", a: "For Indian tax purposes, no. These are US-listed instruments held in your US brokerage account, so the same rules apply: 12.5% long-term after 24 months, slab rate short-term, and Schedule FA disclosure. Dividends need more care because withholding may occur at both the underlying-country and US levels." },
      { q: "How much international-ex-US exposure do I need?", a: "Diminishing returns are real. Going from India-only to India-plus-US changes a portfolio substantially; adding a fourth or fifth regional fund does considerably less while adding cost and complexity. For most investors broad US exposure captures most of the benefit." },
    ],
  },
]

export const featuredArticles = ARTICLES.filter((a) => a.featured)

export const getArticle = (slug: string): Article | undefined =>
  ARTICLES.find((a) => a.slug === slug)

/** Articles belonging to a topic hub, in registry (display) order. */
export const articlesByTopic = (topicId: string): Article[] =>
  ARTICLES.filter((a) => a.topics.includes(topicId))

/**
 * Related reading for an article. Uses the explicit `related` list when the
 * author set one; otherwise ranks the rest of the library by how many topics
 * it shares, breaking ties by registry order so results are deterministic
 * (which matters — a random tie-break would break hydration).
 */
export const getRelatedArticles = (article: Article, limit = 3): Article[] => {
  if (article.related?.length) {
    return article.related
      .map(getArticle)
      .filter((a): a is Article => Boolean(a) && a!.slug !== article.slug)
      .slice(0, limit)
  }

  return ARTICLES.filter((a) => a.slug !== article.slug)
    .map((a) => ({
      article: a,
      overlap: a.topics.filter((t) => article.topics.includes(t)).length,
    }))
    .filter((x) => x.overlap > 0)
    .sort((a, b) => b.overlap - a.overlap)
    .slice(0, limit)
    .map((x) => x.article)
}
