import type { Instrument } from "./types";

/**
 * Fictional market data, ported verbatim from the Stock Terminal Lux design
 * source. Every price on screen derives from these numbers plus a seeded PRNG,
 * so the terminal is fully deterministic — no network, no keys, and identical
 * output on the server and in the browser.
 */
export const INSTRUMENTS: Instrument[] = [
  {
    id: "AAPL",
    short: "Apple",
    name: "Apple Inc.",
    ex: "NASDAQ: AAPL",
    mark: "A",
    color: "#E5DDD1",
    price: 147.04,
    chg: 1.47,
    seed: 7,
    sector: "Consumer electronics",
    mcap: "2.41T",
    pe: 28.4,
    eps: 6.11,
    div: "0.55%",
    beta: 1.24,
    ps: 7.2,
    pb: 44.6,
    roe: "147.9%",
    margin: "25.3%",
    debt: 1.95,
    rev: [274, 365, 394, 383, 391],
    analysts: 42,
    target: 186,
    site: "https://www.apple.com",
    ir: "https://investor.apple.com",
    about:
      "Apple Inc. designs and sells smartphones, personal computers, tablets, wearables and accessories, and operates one of the largest software and services businesses in the world. Headquartered in Cupertino, California.",
    share: [
      { label: "Apple", pct: 24 },
      { label: "Samsung", pct: 20 },
      { label: "Xiaomi", pct: 13 },
      { label: "Others", pct: 43 },
    ],
    comps: [
      { id: "MSFT", name: "Microsoft", price: 418.2, mcap: "3.11T", pe: 36.1, ret: 29.4 },
      { id: "GOOGL", name: "Alphabet", price: 176.5, mcap: "2.18T", pe: 24.8, ret: 41.2 },
      { id: "AMZN", name: "Amazon", price: 184.7, mcap: "1.92T", pe: 52.3, ret: 33.8 },
      { id: "META", name: "Meta", price: 502.3, mcap: "1.28T", pe: 27.6, ret: 63.5 },
      { id: "DELL", name: "Dell Technologies", price: 122.4, mcap: "88B", pe: 21.4, ret: -4.2 },
    ],
    holders: [
      { name: "Vanguard Group", shares: "1.32B", pct: "8.4%" },
      { name: "BlackRock", shares: "1.05B", pct: "6.7%" },
      { name: "Berkshire Hathaway", shares: "905M", pct: "5.8%" },
      { name: "State Street", shares: "587M", pct: "3.7%" },
      { name: "Geode Capital", shares: "333M", pct: "2.1%" },
    ],
    insights: [
      {
        kind: "up",
        title: "Momentum turning positive",
        body: "Price reclaimed the 50-day moving average on above-average volume for three consecutive sessions.",
      },
      {
        kind: "note",
        title: "Services mix expanding",
        body: "Services revenue now accounts for roughly a quarter of total revenue at materially higher gross margin.",
      },
      {
        kind: "warn",
        title: "Valuation stretched",
        body: "Trading near the top of its five-year P/E range, leaving limited room for multiple expansion.",
      },
    ],
    news: [
      { source: "bloomberg.com", title: "Apple plans extreme sports watch with larger screen and metal case", summary: "A ruggedised watch aimed at endurance athletes, with a larger display and a titanium case. It would sit above the current line on price, which matters more for the average selling price of the category than for unit volume.", time: "3 days ago", tag: "HARDWARE" },
      { source: "reuters.com", title: "Services revenue hits new quarterly record as installed base grows", summary: "Services — the App Store, subscriptions and payments — reached a new quarterly high. This segment carries roughly double the gross margin of hardware, so mix shifting toward it lifts profitability even when device sales are flat.", time: "5 days ago", tag: "EARNINGS" },
      { source: "ft.com", title: "Supply chain shifts add capacity outside China for flagship line", summary: "Assembly capacity for the flagship device is being added in India and Vietnam. The near-term cost is duplicated tooling; the longer-term aim is insulation from a single point of geographic risk.", time: "1 week ago", tag: "SUPPLY" },
    ],
  },
  {
    id: "TSLA",
    short: "Tesla",
    name: "Tesla, Inc.",
    ex: "NASDAQ: TSLA",
    mark: "T",
    color: "#E0796B",
    price: 238.45,
    chg: -2.31,
    seed: 19,
    sector: "Electric vehicles",
    mcap: "758B",
    pe: 62.7,
    eps: 3.81,
    div: "—",
    beta: 2.04,
    ps: 7.9,
    pb: 11.2,
    roe: "21.4%",
    margin: "9.6%",
    debt: 0.42,
    rev: [31.5, 53.8, 81.5, 96.8, 97.7],
    analysts: 48,
    target: 214,
    site: "https://www.tesla.com",
    ir: "https://ir.tesla.com",
    about:
      "Tesla designs, manufactures and sells electric vehicles, energy generation and storage systems. Its operations span vehicle production, autonomy software, charging infrastructure and grid-scale batteries.",
    share: [
      { label: "Tesla", pct: 18 },
      { label: "BYD", pct: 22 },
      { label: "VW Group", pct: 9 },
      { label: "Others", pct: 51 },
    ],
    comps: [
      { id: "BYDDY", name: "BYD", price: 58.4, mcap: "96B", pe: 22.1, ret: 18.4 },
      { id: "RIVN", name: "Rivian", price: 13.7, mcap: "13B", pe: -8.4, ret: -42.6 },
      { id: "LCID", name: "Lucid", price: 3.2, mcap: "7B", pe: -4.1, ret: -58.3 },
      { id: "F", name: "Ford Motor", price: 12.1, mcap: "48B", pe: 11.4, ret: -6.7 },
      { id: "GM", name: "General Motors", price: 46.8, mcap: "53B", pe: 5.6, ret: 21.9 },
    ],
    holders: [
      { name: "Vanguard Group", shares: "227M", pct: "7.1%" },
      { name: "BlackRock", shares: "185M", pct: "5.8%" },
      { name: "State Street", shares: "98M", pct: "3.1%" },
      { name: "Capital Research", shares: "74M", pct: "2.3%" },
      { name: "Geode Capital", shares: "66M", pct: "2.1%" },
    ],
    insights: [
      {
        kind: "warn",
        title: "Margin compression",
        body: "Automotive gross margin has contracted for four straight quarters as price cuts flow through.",
      },
      {
        kind: "up",
        title: "Energy storage inflection",
        body: "Deployments are growing faster than the vehicle business and carry structurally higher margin.",
      },
      {
        kind: "note",
        title: "High beta profile",
        body: "Moves roughly twice the market — position sizing matters more than usual here.",
      },
    ],
    news: [
      { source: "reuters.com", title: "Energy storage deployments set a quarterly record as grid demand climbs", summary: "Grid-scale battery deployments hit a record as utilities contract for firming capacity. Storage carries better margins than vehicles and is not exposed to the same price competition.", time: "2 days ago", tag: "ENERGY" },
      { source: "bloomberg.com", title: "Next-generation platform targeted for volume production next year", summary: "The next vehicle platform is guided to volume production next year. The number to watch is cost per unit at scale, not the launch date — every previous platform reached volume later than first indicated.", time: "4 days ago", tag: "PRODUCT" },
      { source: "wsj.com", title: "Price adjustments across major markets pressure near-term margin", summary: "Prices have been cut again across major markets to defend volume. Automotive gross margin absorbs this immediately while the volume benefit, if it arrives, shows up over the following quarters.", time: "1 week ago", tag: "PRICING" },
    ],
  },
  {
    id: "NVDA",
    short: "NVIDIA",
    name: "NVIDIA Corp.",
    ex: "NASDAQ: NVDA",
    mark: "N",
    color: "#93C7A8",
    price: 126.09,
    chg: 3.84,
    seed: 31,
    sector: "Semiconductors",
    mcap: "3.10T",
    pe: 64.2,
    eps: 1.96,
    div: "0.03%",
    beta: 1.68,
    ps: 34.1,
    pb: 58.7,
    roe: "119.2%",
    margin: "53.4%",
    debt: 0.17,
    rev: [16.7, 26.9, 27.0, 60.9, 96.3],
    analysts: 56,
    target: 158,
    site: "https://www.nvidia.com",
    ir: "https://investor.nvidia.com",
    about:
      "NVIDIA builds accelerated computing platforms — graphics processors, networking and software — used for AI training and inference, professional visualisation, gaming and autonomous systems.",
    share: [
      { label: "NVIDIA", pct: 82 },
      { label: "AMD", pct: 9 },
      { label: "Intel", pct: 5 },
      { label: "Others", pct: 4 },
    ],
    comps: [
      { id: "AMD", name: "AMD", price: 158.2, mcap: "256B", pe: 48.7, ret: 12.4 },
      { id: "AVGO", name: "Broadcom", price: 172.6, mcap: "805B", pe: 38.2, ret: 64.8 },
      { id: "INTC", name: "Intel", price: 22.4, mcap: "96B", pe: -12.4, ret: -38.2 },
      { id: "TSM", name: "TSMC", price: 176.9, mcap: "918B", pe: 28.4, ret: 72.1 },
      { id: "MU", name: "Micron", price: 102.3, mcap: "113B", pe: 18.9, ret: 41.6 },
    ],
    holders: [
      { name: "Vanguard Group", shares: "203M", pct: "8.3%" },
      { name: "BlackRock", shares: "176M", pct: "7.2%" },
      { name: "FMR LLC", shares: "137M", pct: "5.6%" },
      { name: "State Street", shares: "98M", pct: "4.0%" },
      { name: "T. Rowe Price", shares: "61M", pct: "2.5%" },
    ],
    insights: [
      {
        kind: "up",
        title: "Demand exceeds supply",
        body: "Data-centre backlog continues to extend beyond current manufacturing capacity.",
      },
      {
        kind: "note",
        title: "Software moat deepening",
        body: "Developer ecosystem lock-in remains the least-priced part of the story.",
      },
      {
        kind: "warn",
        title: "Concentration risk",
        body: "A handful of hyperscale customers account for a large share of revenue.",
      },
    ],
    news: [
      { source: "bloomberg.com", title: "Next-generation accelerator ramps ahead of schedule at foundry partners", summary: "The next accelerator generation is ramping earlier than planned at foundry partners. Supply, not demand, has been the binding constraint, so an earlier ramp converts more directly into revenue than usual.", time: "1 day ago", tag: "SEMIS" },
      { source: "reuters.com", title: "Hyperscaler capital expenditure guidance raised again for the coming year", summary: "The largest cloud buyers raised capital-expenditure guidance again. Roughly a third of that spending has been landing on accelerated computing, which is the demand signal underneath the current order book.", time: "3 days ago", tag: "CAPEX" },
      { source: "ft.com", title: "Networking attach rate becomes the quiet growth driver", summary: "Networking hardware sold alongside accelerators is growing faster than the accelerators themselves. It is a smaller line, but it raises the revenue attached to each deployment.", time: "6 days ago", tag: "ANALYSIS" },
    ],
  },
  {
    id: "AMZN",
    short: "Amazon",
    name: "Amazon.com, Inc.",
    ex: "NASDAQ: AMZN",
    mark: "Z",
    color: "#D9BD8B",
    price: 184.72,
    chg: 0.92,
    seed: 43,
    sector: "E-commerce & cloud",
    mcap: "1.92T",
    pe: 52.3,
    eps: 3.53,
    div: "—",
    beta: 1.15,
    ps: 3.3,
    pb: 8.6,
    roe: "19.8%",
    margin: "7.4%",
    debt: 0.55,
    rev: [386, 470, 514, 575, 638],
    analysts: 51,
    target: 212,
    site: "https://www.amazon.com",
    ir: "https://ir.aboutamazon.com",
    about:
      "Amazon operates online and physical retail marketplaces, a global logistics network, advertising, and Amazon Web Services — the largest public cloud infrastructure provider.",
    share: [
      { label: "Amazon", pct: 31 },
      { label: "Microsoft", pct: 24 },
      { label: "Google", pct: 11 },
      { label: "Others", pct: 34 },
    ],
    comps: [
      { id: "MSFT", name: "Microsoft", price: 418.2, mcap: "3.11T", pe: 36.1, ret: 29.4 },
      { id: "GOOGL", name: "Alphabet", price: 176.5, mcap: "2.18T", pe: 24.8, ret: 41.2 },
      { id: "BABA", name: "Alibaba", price: 82.4, mcap: "198B", pe: 15.7, ret: -8.3 },
      { id: "SHOP", name: "Shopify", price: 68.9, mcap: "88B", pe: 72.4, ret: 34.7 },
      { id: "WMT", name: "Walmart", price: 72.1, mcap: "581B", pe: 31.2, ret: 44.9 },
    ],
    holders: [
      { name: "Vanguard Group", shares: "745M", pct: "7.2%" },
      { name: "BlackRock", shares: "620M", pct: "6.0%" },
      { name: "State Street", shares: "340M", pct: "3.3%" },
      { name: "FMR LLC", shares: "297M", pct: "2.9%" },
      { name: "T. Rowe Price", shares: "188M", pct: "1.8%" },
    ],
    insights: [
      {
        kind: "up",
        title: "Cloud reacceleration",
        body: "AWS growth has ticked up for two consecutive quarters after a long optimisation cycle.",
      },
      {
        kind: "note",
        title: "Advertising compounding",
        body: "Advertising is now the third pillar and grows faster than retail at far higher margin.",
      },
      {
        kind: "warn",
        title: "Capital intensity",
        body: "Infrastructure spend keeps free cash flow volatile quarter to quarter.",
      },
    ],
    news: [
      { source: "reuters.com", title: "Logistics network redesign cuts cost to serve for a third straight year", summary: "A third consecutive year of falling cost to serve, from regionalised inventory and shorter delivery routes. It flows straight to retail operating margin, historically the thinnest part of the business.", time: "2 days ago", tag: "LOGISTICS" },
      { source: "bloomberg.com", title: "Cloud unit signs multi-year capacity deals with AI startups", summary: "Multi-year capacity commitments signed with AI companies. These are contracted backlog rather than recognised revenue — useful for visibility, but the cash arrives over the life of the deal.", time: "4 days ago", tag: "CLOUD" },
      { source: "cnbc.com", title: "Advertising segment posts fastest growth in the portfolio", summary: "Advertising is now the fastest-growing segment. It is high-margin and sits on traffic the business already has, which is why it changes the profit mix faster than its size suggests.", time: "1 week ago", tag: "ADVERTISING" },
    ],
  },
  {
    id: "SPOT",
    short: "Spotify",
    name: "Spotify Technology",
    ex: "NYSE: SPOT",
    mark: "S",
    color: "#93C7A8",
    price: 312.68,
    chg: 1.18,
    seed: 57,
    sector: "Audio streaming",
    mcap: "62B",
    pe: 74.8,
    eps: 4.18,
    div: "—",
    beta: 1.62,
    ps: 4.1,
    pb: 14.3,
    roe: "21.1%",
    margin: "5.2%",
    debt: 0.11,
    rev: [9.7, 11.4, 13.2, 15.1, 17.0],
    analysts: 34,
    target: 348,
    site: "https://www.spotify.com",
    ir: "https://investors.spotify.com",
    about:
      "Spotify operates the largest audio streaming subscription service, spanning music, podcasts and audiobooks across more than 180 markets, monetised through premium subscriptions and advertising.",
    share: [
      { label: "Spotify", pct: 31 },
      { label: "Apple Music", pct: 15 },
      { label: "YouTube", pct: 13 },
      { label: "Others", pct: 41 },
    ],
    comps: [
      { id: "NFLX", name: "Netflix", price: 678.4, mcap: "292B", pe: 44.2, ret: 52.8 },
      { id: "WMG", name: "Warner Music", price: 31.2, mcap: "16B", pe: 28.4, ret: -6.1 },
      { id: "UMG", name: "Universal Music", price: 27.8, mcap: "50B", pe: 31.7, ret: 9.4 },
      { id: "SIRI", name: "SiriusXM", price: 24.6, mcap: "9B", pe: 7.8, ret: -31.2 },
      { id: "LYV", name: "Live Nation", price: 102.7, mcap: "23B", pe: 48.1, ret: 18.6 },
    ],
    holders: [
      { name: "Baillie Gifford", shares: "13.4M", pct: "6.8%" },
      { name: "Morgan Stanley", shares: "11.2M", pct: "5.7%" },
      { name: "T. Rowe Price", shares: "9.8M", pct: "5.0%" },
      { name: "Vanguard Group", shares: "7.1M", pct: "3.6%" },
      { name: "BlackRock", shares: "5.4M", pct: "2.7%" },
    ],
    insights: [
      {
        kind: "up",
        title: "Gross margin expansion",
        body: "Price increases and a better content mix have lifted gross margin above 31%.",
      },
      {
        kind: "note",
        title: "Audiobook bundling",
        body: "Attach rates on the bundled tier are running ahead of internal plan.",
      },
      {
        kind: "warn",
        title: "Label dependency",
        body: "Royalty economics remain concentrated with three major rights holders.",
      },
    ],
    news: [
      { source: "bloomberg.com", title: "Premium tier price rise lands with lower churn than modelled", summary: "A price increase on the premium tier produced less cancellation than forecast. That is the cleanest available evidence of pricing power, and it lifts revenue per user without any new subscribers.", time: "1 day ago", tag: "PRICING" },
      { source: "ft.com", title: "Audiobook catalogue expansion targets new subscriber cohorts", summary: "The audiobook catalogue is being expanded to reach listeners the music product does not. Content costs are fixed while listening is not, so the economics improve with engagement.", time: "5 days ago", tag: "PRODUCT" },
      { source: "reuters.com", title: "Advertising business restructured around programmatic buying", summary: "The advertising business has been rebuilt around automated buying. It lowers the cost of selling inventory and opens the platform to advertisers too small for a direct sales team.", time: "1 week ago", tag: "ADVERTISING" },
    ],
  },
  {
    id: "MSFT",
    short: "Microsoft",
    name: "Microsoft Corp.",
    ex: "NASDAQ: MSFT",
    mark: "M",
    color: "#B0BFCB",
    price: 418.23,
    chg: 0.64,
    seed: 71,
    sector: "Software & cloud",
    mcap: "3.11T",
    pe: 36.1,
    eps: 11.58,
    div: "0.72%",
    beta: 0.91,
    ps: 12.8,
    pb: 11.4,
    roe: "38.4%",
    margin: "36.1%",
    debt: 0.31,
    rev: [168, 198, 212, 228, 245],
    analysts: 58,
    target: 472,
    site: "https://www.microsoft.com",
    ir: "https://www.microsoft.com/en-us/investor",
    about:
      "Microsoft develops and licenses software, cloud infrastructure and productivity services, including Azure, Microsoft 365, Dynamics, Windows, and gaming through Xbox.",
    share: [
      { label: "Microsoft", pct: 24 },
      { label: "Amazon", pct: 31 },
      { label: "Google", pct: 11 },
      { label: "Others", pct: 34 },
    ],
    comps: [
      { id: "AAPL", name: "Apple", price: 147.0, mcap: "2.41T", pe: 28.4, ret: 18.7 },
      { id: "GOOGL", name: "Alphabet", price: 176.5, mcap: "2.18T", pe: 24.8, ret: 41.2 },
      { id: "CRM", name: "Salesforce", price: 268.4, mcap: "259B", pe: 44.8, ret: 22.3 },
      { id: "ORCL", name: "Oracle", price: 142.7, mcap: "394B", pe: 38.6, ret: 48.1 },
      { id: "NOW", name: "ServiceNow", price: 812.6, mcap: "167B", pe: 68.2, ret: 36.9 },
    ],
    holders: [
      { name: "Vanguard Group", shares: "677M", pct: "9.1%" },
      { name: "BlackRock", shares: "570M", pct: "7.7%" },
      { name: "State Street", shares: "303M", pct: "4.1%" },
      { name: "FMR LLC", shares: "215M", pct: "2.9%" },
      { name: "Geode Capital", shares: "162M", pct: "2.2%" },
    ],
    insights: [
      {
        kind: "up",
        title: "Azure share gains",
        body: "Cloud growth continues to outpace the broader infrastructure market.",
      },
      {
        kind: "note",
        title: "Assistant monetisation",
        body: "Seat-based AI add-ons are converting inside the existing enterprise base.",
      },
      {
        kind: "warn",
        title: "Capex cycle",
        body: "Data-centre build-out is compressing near-term free cash flow conversion.",
      },
    ],
    news: [
      { source: "reuters.com", title: "Enterprise agreements bundle AI assistants across the productivity suite", summary: "AI assistants are being bundled into enterprise agreements across the productivity suite. Bundling raises revenue per seat without requiring a separate purchase decision from the customer.", time: "2 days ago", tag: "CLOUD" },
      { source: "bloomberg.com", title: "Data-centre expansion announced across three new regions", summary: "Three new data-centre regions announced. Capacity has been the constraint on cloud growth, so new regions unlock demand that already exists rather than creating it.", time: "4 days ago", tag: "CAPEX" },
      { source: "cnbc.com", title: "Gaming division posts record engagement hours", summary: "Record engagement hours in the gaming division. Engagement precedes subscription and in-game revenue, so it is a leading indicator for that segment rather than a result in itself.", time: "1 week ago", tag: "GAMING" },
    ],
  },
];

export const DEFAULT_TICKER = "AAPL";

export function getInstrument(id: string): Instrument {
  return INSTRUMENTS.find((s) => s.id === id) ?? INSTRUMENTS[0];
}
