/**
 * Which stock pages are built ahead of time.
 *
 * THE MEASUREMENT
 *
 * Six were, out of roughly 13,900. Every other ticker was assembled on its
 * first visit, and against production that costs 8-15 seconds — ADBE 7.7s,
 * CRM 15.0s, ORCL 30.7s — then 0.5s on every visit afterwards. Exactly one
 * reader pays, and with six pages prerendered almost every reader is that one.
 *
 * The live feed cannot help. A stock page is about thirty upstream calls —
 * profile, filings, five years of daily history, three indicators, short
 * interest, intraday, the SPY benchmark, news, and up to eight peers — and the
 * websocket carries prices only, onto a page that already exists. It keeps the
 * number ticking; it cannot build the furniture around it.
 *
 * WHERE THE LIST COMES FROM
 *
 * lib/market/data/baseline.json: 3,000 rows of one real sweep, committed, and
 * already ordered by turnover. Reading a committed file costs no network call
 * at build time, and that matters more than it sounds — `next build` prerenders
 * across nine worker processes that do not share a cache, so anything derived
 * live would be derived nine times. That is precisely how nine full market
 * sweeps and nine build timeouts happened before.
 *
 * WHY NOT ALL OF THEM
 *
 * Each prerendered page is about 1.8 MB of build output. Five hundred is
 * roughly 0.9 GB; the whole universe would be 25 GB, and could never be kept
 * warm regardless — a page is only prerendered until its TTL expires, and
 * re-rendering 13,900 pages inside any sane window is not reachable on this
 * box. Five hundred covers the names people actually open.
 */

/**
 * Sized for a build budget, not for a market. Tunable per build; see the page.
 *
 * This was briefly lowered to 200 on a wrong diagnosis, which is worth keeping
 * on record. The first 500-page deploy never landed, and with no build log to
 * hand the guess was disk or memory — 1.4 GB of output, nine workers. The log,
 * when it arrived, said something else entirely: Render's build machine ran
 * "34 workers", each generating eight pages at once, each page opening about
 * thirteen upstream calls. Roughly 3,500 simultaneous requests to the gateway,
 * which stopped answering, and every page timed out. Nothing about the count
 * was the problem; the machine was too big for an unbounded fan-out.
 *
 * next.config.ts now pins the build to eight workers and four pages each,
 * everywhere. Under that cap 500 builds cleanly — 2m8s, zero timeouts, 502
 * pages — and because the concurrency no longer depends on the hardware, a
 * local build is finally evidence for a deploy. PRERENDER_TICKERS still tunes
 * it per build; the whole universe is not an option at any setting, at ~2.1 MB
 * a page and no way to keep 13,900 of them warm.
 */
export const PRERENDER_LIMIT = 500;

export type PrerenderInput = {
  /** Always built, whatever their turnover — the terminal leads with these. */
  covered: readonly string[];
  /** Swept rows; order is not trusted, turnover is recomputed here. */
  rows: readonly { s: string; px: number; avgVol: number }[];
  limit: number;
  /**
   * Symbols that must never be built. An exchange placeholder renders as a 404
   * and Next bakes that into the prerender — the exact bug that once shipped
   * "Stock not found" on all six covered tickers. Widening to 500 pages
   * multiplies the chance of one slipping through, so the page passes the same
   * predicate it uses at render time.
   */
  skip?: (symbol: string) => boolean;
};

export function prerenderTickers({
  covered,
  rows,
  limit,
  skip,
}: PrerenderInput): string[] {
  const out: string[] = [];
  const seen = new Set<string>();

  const add = (raw: string) => {
    const symbol = raw.trim().toUpperCase();
    if (!symbol || seen.has(symbol)) return;
    if (skip?.(symbol)) return;
    seen.add(symbol);
    out.push(symbol);
  };

  /* The covered names first, so a tight limit never drops the pages the
     terminal itself links to from its own chrome. */
  for (const s of covered) add(s);

  /* Then by typical turnover — price times thirty-day average volume, the same
     measure screen.ts uses for the liquidity floor. Recomputed rather than
     trusting the file's order, because the file is regenerated by hand. */
  const byTurnover = [...rows].sort((a, b) => b.px * b.avgVol - a.px * a.avgVol);
  for (const r of byTurnover) {
    if (out.length >= limit) break;
    add(r.s);
  }

  return out.slice(0, Math.max(limit, 0));
}
